In [1]:
import numpy as np
import time


In [2]:
arr = np.array([12,56,78,90,90])
print(arr[-1])

90


In [3]:
list1 = list(range(100000))
list2 = list(range(100000))
result = []
start = time.time()* 1000
for num1,num2 in zip(list1,list2):
    result.append(num1+num2)
end = time.time() * 1000
print("Time taken by list", end-start)

Time taken by list 16.153564453125


In [4]:
arr1 = np.arange(100000)
arr2 = np.arange(100000)
start = time.time()* 1000
result = arr1 + arr2
end = time.time()* 1000
print("Time taken by array", end-start)


Time taken by array 2.01025390625


In [5]:
arr = np.array([12,67,88,53,90])
arr.ndim

1

In [6]:
mat = np.array([[12,56,78],[12,78,67]])
mat.ndim

2

In [7]:
mat.shape

(2, 3)

In [8]:
mat2 = mat.reshape(-1,2)
mat2

array([[12, 56],
       [78, 12],
       [78, 67]])

In [9]:
mat2.shape

(3, 2)

In [10]:
mat.reshape(3,2)

array([[12, 56],
       [78, 12],
       [78, 67]])

In [11]:
mat.ravel()

array([12, 56, 78, 12, 78, 67])

In [12]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [13]:
np.random.randint(1,20,4)

array([ 3,  6, 19,  1])

In [14]:
np.random.rand(10)

array([0.75166847, 0.83476328, 0.45394131, 0.88553368, 0.76286529,
       0.02576206, 0.73264741, 0.07264761, 0.93400836, 0.4744426 ])

In [15]:
np.random.randn(10)

array([ 1.00273404, -0.37765136, -0.02522533,  0.0259884 ,  0.7211343 ,
       -1.68299188,  2.26781797, -0.21589733, -1.30391747, -0.34160478])